ALTER TABLE CUSTOMERS 
MODIFY COLUMN FullName VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS 
MODIFY COLUMN Email VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS 
ADD CONSTRAINT UC_Email UNIQUE (Email);

ALTER TABLE CUSTOMERS 
ADD CONSTRAINT CHK_Age CHECK (Age > 0);
